#!/usr/bin/env python3
"""Render nginx/templates/default.conf.template from services.json.

Run this after every services.json change (or `docker compose up --build`,
which runs it for you via the Makefile). Nothing secret is written: upstream
credentials stay as ${TOKEN_*} placeholders that nginx substitutes from the
environment at container start.
"""

import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
CONFIG = json.loads((ROOT / "services.json").read_text())
OUT = ROOT / "gateway" / "templates" / "default.conf.template"

TOKEN_RE = re.compile(r"\$\{(TOKEN_[A-Z0-9_]+)\}")

HEAD = """# GENERATED by scripts/gen-nginx-conf.py from services.json — do not edit.
# Any ${TOKEN_*} below is substituted at container start from the environment
# (see NGINX_ENVSUBST_FILTER in docker-compose.yml). nginx's own $variables
# are left alone because they never start with TOKEN_.

server {
    listen 8080;
    server_name _;

    # Big MCP payloads and streaming responses.
    client_max_body_size 100m;
    proxy_http_version 1.1;
    proxy_read_timeout 3600s;
    proxy_buffering off;

    # --- auth server (public: the login flow itself cannot require a login) ---
    location = /register           { proxy_pass http://auth:8000/register; }
    location = /authorize          { proxy_pass http://auth:8000/authorize; }
    location = /token              { proxy_pass http://auth:8000/token; }
    location = /healthz            { proxy_pass http://auth:8000/healthz; }
    location ^~ /.well-known/      { proxy_pass http://auth:8000; }

    # --- internal auth_request target ---
    location = /_verify {
        internal;
        proxy_pass http://auth:8000/verify;
        proxy_pass_request_body off;
        proxy_set_header Content-Length "";
        proxy_set_header X-Original-URI $request_uri;
    }
"""

SERVICE = """
    # --- {name} ---
    location {location} {{
{auth_lines}        proxy_pass {proxy_target};
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
{inject_lines}    }}
"""

AUTH_LINES = """        auth_request /_verify;
        auth_request_set $auth_user $upstream_http_x_auth_user;
        proxy_set_header X-Auth-User $auth_user;
        # Hand 401s back to the client with the WWW-Authenticate header intact,
        # so an MCP client knows where to go and log in.
        error_page 401 = @unauthorized;
"""

TAIL = """
    # The auth service already sends a correct WWW-Authenticate on its 401 and
    # nginx copies it from the subrequest, so adding one here too would send
    # the header twice. Only the JSON body is added.
    location @unauthorized {
        default_type application/json;
        return 401 '{"error":"unauthorized"}';
    }

    location / { return 404 '{"error":"not_found"}'; }
}
"""


def main() -> int:
    tokens: set[str] = set()
    blocks = []

    for svc in CONFIG["services"]:
        name = svc["name"]
        path = svc["path"].rstrip("/")
        upstream = svc["upstream"].rstrip("/")

        # The client's own bearer token is for THIS gateway, not for the
        # upstream — always drop it, unless the upstream credential is itself
        # being injected as Authorization (then the header is overwritten).
        inject_lines = ""
        if "inject" in svc:
            header = svc["inject"]["header"]
            value = svc["inject"]["value"]
            tokens.update(TOKEN_RE.findall(value))
            if header.lower() != "authorization":
                inject_lines += '        proxy_set_header Authorization "";\n'
            inject_lines += f'        proxy_set_header {header} "{value}";\n'
        else:
            inject_lines = '        proxy_set_header Authorization "";\n'

        # strip_path (default true): /foo/bar -> upstream /bar.
        # strip_path false: the full path is preserved, which is what an MCP
        # endpoint needs — the server itself serves /mcp and would 404 on /.
        if svc.get("strip_path", True):
            location, proxy_target = f"{path}/", f"{upstream}/"
        else:
            location, proxy_target = path, upstream

        blocks.append(SERVICE.format(
            name=name,
            location=location,
            proxy_target=proxy_target,
            auth_lines="" if svc.get("public") else AUTH_LINES,
            inject_lines=inject_lines,
        ))

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(HEAD + "".join(blocks) + TAIL)

    print(f"wrote {OUT.relative_to(ROOT)}")
    print(f"services: {', '.join(s['name'] for s in CONFIG['services']) or '(none)'}")
    if tokens:
        print(f"required in .env: {', '.join(sorted(tokens))}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
